version: '3'
services:
    mysql:
        container_name: mblog-mysql
        image: mysql/mysql-server:5.7
        environment:
            MYSQL_DATABASE: db_mblog
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_ROOT_HOST: '%'
            TZ: Asia/Shanghai
        expose:
            - "3306"
        volumes:
            - /data/mblog/mysql/mysql_data:/var/lib/mysql
        restart: always

    server:
        container_name: mblog-server
        image: langhsu/mblog:latest
        build: .
        working_dir: /app/mblog
        environment:
            TZ: Asia/Shanghai
        ports:
            - "8080:8080"
        volumes:
            - /data/mblog/storage:/app/mblog/storage
            - /data/mblog/logs:/app/mblog/logs
        depends_on:
            - mysql
        restart: always